/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tazine_codeplay_version_java1_jni_HelloWorld */

#ifndef _Included_com_tazine_codeplay_version_java1_jni_HelloWorld
#define _Included_com_tazine_codeplay_version_java1_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tazine_codeplay_version_java1_jni_HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tazine_codeplay_version_java1_jni_HelloWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
