// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amap.proto

package com.tazine.third.protobuf.compare;

public final class AmapEntity {
  private AmapEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrafficOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Traffic)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 同上
     * </pre>
     *
     * <code>optional int32 ent = 1;</code>
     */
    int getEnt();

    /**
     * <pre>
     * 同上
     * </pre>
     *
     * <code>optional int32 dip = 2;</code>
     */
    int getDip();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu = 3;</code>
     */
    String getDiu();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu = 3;</code>
     */
    com.google.protobuf.ByteString
        getDiuBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string session = 4;</code>
     */
    String getSession();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string session = 4;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string sign = 5;</code>
     */
    String getSign();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string sign = 5;</code>
     */
    com.google.protobuf.ByteString
        getSignBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 aetraffic = 6;</code>
     */
    int getAetraffic();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string appstartid = 7;</code>
     */
    String getAppstartid();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string appstartid = 7;</code>
     */
    com.google.protobuf.ByteString
        getAppstartidBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string adiu = 8;</code>
     */
    String getAdiu();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string adiu = 8;</code>
     */
    com.google.protobuf.ByteString
        getAdiuBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string cifa = 9;</code>
     */
    String getCifa();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string cifa = 9;</code>
     */
    com.google.protobuf.ByteString
        getCifaBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu2 = 10;</code>
     */
    String getDiu2();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu2 = 10;</code>
     */
    com.google.protobuf.ByteString
        getDiu2Bytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string div = 11;</code>
     */
    String getDiv();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string div = 11;</code>
     */
    com.google.protobuf.ByteString
        getDivBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string output = 12;</code>
     */
    String getOutput();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string output = 12;</code>
     */
    com.google.protobuf.ByteString
        getOutputBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string siv = 13;</code>
     */
    String getSiv();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string siv = 13;</code>
     */
    com.google.protobuf.ByteString
        getSivBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string dic = 14;</code>
     */
    String getDic();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string dic = 14;</code>
     */
    com.google.protobuf.ByteString
        getDicBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string BID_F = 15;</code>
     */
    String getBIDF();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string BID_F = 15;</code>
     */
    com.google.protobuf.ByteString
        getBIDFBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 stepid = 16;</code>
     */
    int getStepid();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu3 = 17;</code>
     */
    String getDiu3();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu3 = 17;</code>
     */
    com.google.protobuf.ByteString
        getDiu3Bytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string spm = 18;</code>
     */
    String getSpm();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string spm = 18;</code>
     */
    com.google.protobuf.ByteString
        getSpmBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string tid = 19;</code>
     */
    String getTid();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string tid = 19;</code>
     */
    com.google.protobuf.ByteString
        getTidBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 uid = 20;</code>
     */
    int getUid();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 dibv = 21;</code>
     */
    int getDibv();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string channel = 22;</code>
     */
    String getChannel();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string channel = 22;</code>
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 client_network_class = 23;</code>
     */
    int getClientNetworkClass();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string csid = 24;</code>
     */
    String getCsid();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string csid = 24;</code>
     */
    com.google.protobuf.ByteString
        getCsidBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 accs = 25;</code>
     */
    int getAccs();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string gsid = 26;</code>
     */
    String getGsid();
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string gsid = 26;</code>
     */
    com.google.protobuf.ByteString
        getGsidBytes();
  }
  /**
   * Protobuf type {@code Traffic}
   */
  public  static final class Traffic extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Traffic)
      TrafficOrBuilder {
    // Use Traffic.newBuilder() to construct.
    private Traffic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Traffic() {
      ent_ = 0;
      dip_ = 0;
      diu_ = "";
      session_ = "";
      sign_ = "";
      aetraffic_ = 0;
      appstartid_ = "";
      adiu_ = "";
      cifa_ = "";
      diu2_ = "";
      div_ = "";
      output_ = "";
      siv_ = "";
      dic_ = "";
      bIDF_ = "";
      stepid_ = 0;
      diu3_ = "";
      spm_ = "";
      tid_ = "";
      uid_ = 0;
      dibv_ = 0;
      channel_ = "";
      clientNetworkClass_ = 0;
      csid_ = "";
      accs_ = 0;
      gsid_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Traffic(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              ent_ = input.readInt32();
              break;
            }
            case 16: {

              dip_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              diu_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              sign_ = s;
              break;
            }
            case 48: {

              aetraffic_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              appstartid_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              adiu_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              cifa_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              diu2_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              div_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              output_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              siv_ = s;
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              dic_ = s;
              break;
            }
            case 122: {
              String s = input.readStringRequireUtf8();

              bIDF_ = s;
              break;
            }
            case 128: {

              stepid_ = input.readInt32();
              break;
            }
            case 138: {
              String s = input.readStringRequireUtf8();

              diu3_ = s;
              break;
            }
            case 146: {
              String s = input.readStringRequireUtf8();

              spm_ = s;
              break;
            }
            case 154: {
              String s = input.readStringRequireUtf8();

              tid_ = s;
              break;
            }
            case 160: {

              uid_ = input.readInt32();
              break;
            }
            case 168: {

              dibv_ = input.readInt32();
              break;
            }
            case 178: {
              String s = input.readStringRequireUtf8();

              channel_ = s;
              break;
            }
            case 184: {

              clientNetworkClass_ = input.readInt32();
              break;
            }
            case 194: {
              String s = input.readStringRequireUtf8();

              csid_ = s;
              break;
            }
            case 200: {

              accs_ = input.readInt32();
              break;
            }
            case 210: {
              String s = input.readStringRequireUtf8();

              gsid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AmapEntity.internal_static_Traffic_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AmapEntity.internal_static_Traffic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Traffic.class, Builder.class);
    }

    public static final int ENT_FIELD_NUMBER = 1;
    private int ent_;
    /**
     * <pre>
     * 同上
     * </pre>
     *
     * <code>optional int32 ent = 1;</code>
     */
    public int getEnt() {
      return ent_;
    }

    public static final int DIP_FIELD_NUMBER = 2;
    private int dip_;
    /**
     * <pre>
     * 同上
     * </pre>
     *
     * <code>optional int32 dip = 2;</code>
     */
    public int getDip() {
      return dip_;
    }

    public static final int DIU_FIELD_NUMBER = 3;
    private volatile Object diu_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu = 3;</code>
     */
    public String getDiu() {
      Object ref = diu_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        diu_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDiuBytes() {
      Object ref = diu_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        diu_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSION_FIELD_NUMBER = 4;
    private volatile Object session_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string session = 4;</code>
     */
    public String getSession() {
      Object ref = session_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string session = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      Object ref = session_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGN_FIELD_NUMBER = 5;
    private volatile Object sign_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string sign = 5;</code>
     */
    public String getSign() {
      Object ref = sign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string sign = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AETRAFFIC_FIELD_NUMBER = 6;
    private int aetraffic_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 aetraffic = 6;</code>
     */
    public int getAetraffic() {
      return aetraffic_;
    }

    public static final int APPSTARTID_FIELD_NUMBER = 7;
    private volatile Object appstartid_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string appstartid = 7;</code>
     */
    public String getAppstartid() {
      Object ref = appstartid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appstartid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string appstartid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAppstartidBytes() {
      Object ref = appstartid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appstartid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADIU_FIELD_NUMBER = 8;
    private volatile Object adiu_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string adiu = 8;</code>
     */
    public String getAdiu() {
      Object ref = adiu_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        adiu_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string adiu = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAdiuBytes() {
      Object ref = adiu_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        adiu_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CIFA_FIELD_NUMBER = 9;
    private volatile Object cifa_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string cifa = 9;</code>
     */
    public String getCifa() {
      Object ref = cifa_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cifa_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string cifa = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCifaBytes() {
      Object ref = cifa_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cifa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIU2_FIELD_NUMBER = 10;
    private volatile Object diu2_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu2 = 10;</code>
     */
    public String getDiu2() {
      Object ref = diu2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        diu2_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu2 = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDiu2Bytes() {
      Object ref = diu2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        diu2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIV_FIELD_NUMBER = 11;
    private volatile Object div_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string div = 11;</code>
     */
    public String getDiv() {
      Object ref = div_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        div_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string div = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDivBytes() {
      Object ref = div_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        div_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OUTPUT_FIELD_NUMBER = 12;
    private volatile Object output_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string output = 12;</code>
     */
    public String getOutput() {
      Object ref = output_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        output_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string output = 12;</code>
     */
    public com.google.protobuf.ByteString
        getOutputBytes() {
      Object ref = output_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIV_FIELD_NUMBER = 13;
    private volatile Object siv_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string siv = 13;</code>
     */
    public String getSiv() {
      Object ref = siv_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        siv_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string siv = 13;</code>
     */
    public com.google.protobuf.ByteString
        getSivBytes() {
      Object ref = siv_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        siv_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIC_FIELD_NUMBER = 14;
    private volatile Object dic_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string dic = 14;</code>
     */
    public String getDic() {
      Object ref = dic_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dic_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string dic = 14;</code>
     */
    public com.google.protobuf.ByteString
        getDicBytes() {
      Object ref = dic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BID_F_FIELD_NUMBER = 15;
    private volatile Object bIDF_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string BID_F = 15;</code>
     */
    public String getBIDF() {
      Object ref = bIDF_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bIDF_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string BID_F = 15;</code>
     */
    public com.google.protobuf.ByteString
        getBIDFBytes() {
      Object ref = bIDF_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bIDF_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STEPID_FIELD_NUMBER = 16;
    private int stepid_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 stepid = 16;</code>
     */
    public int getStepid() {
      return stepid_;
    }

    public static final int DIU3_FIELD_NUMBER = 17;
    private volatile Object diu3_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu3 = 17;</code>
     */
    public String getDiu3() {
      Object ref = diu3_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        diu3_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string diu3 = 17;</code>
     */
    public com.google.protobuf.ByteString
        getDiu3Bytes() {
      Object ref = diu3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        diu3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPM_FIELD_NUMBER = 18;
    private volatile Object spm_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string spm = 18;</code>
     */
    public String getSpm() {
      Object ref = spm_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        spm_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string spm = 18;</code>
     */
    public com.google.protobuf.ByteString
        getSpmBytes() {
      Object ref = spm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        spm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TID_FIELD_NUMBER = 19;
    private volatile Object tid_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string tid = 19;</code>
     */
    public String getTid() {
      Object ref = tid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string tid = 19;</code>
     */
    public com.google.protobuf.ByteString
        getTidBytes() {
      Object ref = tid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID_FIELD_NUMBER = 20;
    private int uid_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 uid = 20;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int DIBV_FIELD_NUMBER = 21;
    private int dibv_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 dibv = 21;</code>
     */
    public int getDibv() {
      return dibv_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 22;
    private volatile Object channel_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string channel = 22;</code>
     */
    public String getChannel() {
      Object ref = channel_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string channel = 22;</code>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      Object ref = channel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_NETWORK_CLASS_FIELD_NUMBER = 23;
    private int clientNetworkClass_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 client_network_class = 23;</code>
     */
    public int getClientNetworkClass() {
      return clientNetworkClass_;
    }

    public static final int CSID_FIELD_NUMBER = 24;
    private volatile Object csid_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string csid = 24;</code>
     */
    public String getCsid() {
      Object ref = csid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        csid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string csid = 24;</code>
     */
    public com.google.protobuf.ByteString
        getCsidBytes() {
      Object ref = csid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        csid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCS_FIELD_NUMBER = 25;
    private int accs_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 accs = 25;</code>
     */
    public int getAccs() {
      return accs_;
    }

    public static final int GSID_FIELD_NUMBER = 26;
    private volatile Object gsid_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string gsid = 26;</code>
     */
    public String getGsid() {
      Object ref = gsid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gsid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional string gsid = 26;</code>
     */
    public com.google.protobuf.ByteString
        getGsidBytes() {
      Object ref = gsid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gsid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ent_ != 0) {
        output.writeInt32(1, ent_);
      }
      if (dip_ != 0) {
        output.writeInt32(2, dip_);
      }
      if (!getDiuBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, diu_);
      }
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, session_);
      }
      if (!getSignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sign_);
      }
      if (aetraffic_ != 0) {
        output.writeInt32(6, aetraffic_);
      }
      if (!getAppstartidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, appstartid_);
      }
      if (!getAdiuBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, adiu_);
      }
      if (!getCifaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, cifa_);
      }
      if (!getDiu2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, diu2_);
      }
      if (!getDivBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, div_);
      }
      if (!getOutputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, output_);
      }
      if (!getSivBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, siv_);
      }
      if (!getDicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, dic_);
      }
      if (!getBIDFBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, bIDF_);
      }
      if (stepid_ != 0) {
        output.writeInt32(16, stepid_);
      }
      if (!getDiu3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, diu3_);
      }
      if (!getSpmBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, spm_);
      }
      if (!getTidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 19, tid_);
      }
      if (uid_ != 0) {
        output.writeInt32(20, uid_);
      }
      if (dibv_ != 0) {
        output.writeInt32(21, dibv_);
      }
      if (!getChannelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 22, channel_);
      }
      if (clientNetworkClass_ != 0) {
        output.writeInt32(23, clientNetworkClass_);
      }
      if (!getCsidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 24, csid_);
      }
      if (accs_ != 0) {
        output.writeInt32(25, accs_);
      }
      if (!getGsidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 26, gsid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ent_);
      }
      if (dip_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dip_);
      }
      if (!getDiuBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, diu_);
      }
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, session_);
      }
      if (!getSignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sign_);
      }
      if (aetraffic_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, aetraffic_);
      }
      if (!getAppstartidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, appstartid_);
      }
      if (!getAdiuBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, adiu_);
      }
      if (!getCifaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, cifa_);
      }
      if (!getDiu2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, diu2_);
      }
      if (!getDivBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, div_);
      }
      if (!getOutputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, output_);
      }
      if (!getSivBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, siv_);
      }
      if (!getDicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, dic_);
      }
      if (!getBIDFBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, bIDF_);
      }
      if (stepid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, stepid_);
      }
      if (!getDiu3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, diu3_);
      }
      if (!getSpmBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, spm_);
      }
      if (!getTidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, tid_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, uid_);
      }
      if (dibv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, dibv_);
      }
      if (!getChannelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, channel_);
      }
      if (clientNetworkClass_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, clientNetworkClass_);
      }
      if (!getCsidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(24, csid_);
      }
      if (accs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(25, accs_);
      }
      if (!getGsidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(26, gsid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Traffic)) {
        return super.equals(obj);
      }
      Traffic other = (Traffic) obj;

      boolean result = true;
      result = result && (getEnt()
          == other.getEnt());
      result = result && (getDip()
          == other.getDip());
      result = result && getDiu()
          .equals(other.getDiu());
      result = result && getSession()
          .equals(other.getSession());
      result = result && getSign()
          .equals(other.getSign());
      result = result && (getAetraffic()
          == other.getAetraffic());
      result = result && getAppstartid()
          .equals(other.getAppstartid());
      result = result && getAdiu()
          .equals(other.getAdiu());
      result = result && getCifa()
          .equals(other.getCifa());
      result = result && getDiu2()
          .equals(other.getDiu2());
      result = result && getDiv()
          .equals(other.getDiv());
      result = result && getOutput()
          .equals(other.getOutput());
      result = result && getSiv()
          .equals(other.getSiv());
      result = result && getDic()
          .equals(other.getDic());
      result = result && getBIDF()
          .equals(other.getBIDF());
      result = result && (getStepid()
          == other.getStepid());
      result = result && getDiu3()
          .equals(other.getDiu3());
      result = result && getSpm()
          .equals(other.getSpm());
      result = result && getTid()
          .equals(other.getTid());
      result = result && (getUid()
          == other.getUid());
      result = result && (getDibv()
          == other.getDibv());
      result = result && getChannel()
          .equals(other.getChannel());
      result = result && (getClientNetworkClass()
          == other.getClientNetworkClass());
      result = result && getCsid()
          .equals(other.getCsid());
      result = result && (getAccs()
          == other.getAccs());
      result = result && getGsid()
          .equals(other.getGsid());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ENT_FIELD_NUMBER;
      hash = (53 * hash) + getEnt();
      hash = (37 * hash) + DIP_FIELD_NUMBER;
      hash = (53 * hash) + getDip();
      hash = (37 * hash) + DIU_FIELD_NUMBER;
      hash = (53 * hash) + getDiu().hashCode();
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      hash = (37 * hash) + SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getSign().hashCode();
      hash = (37 * hash) + AETRAFFIC_FIELD_NUMBER;
      hash = (53 * hash) + getAetraffic();
      hash = (37 * hash) + APPSTARTID_FIELD_NUMBER;
      hash = (53 * hash) + getAppstartid().hashCode();
      hash = (37 * hash) + ADIU_FIELD_NUMBER;
      hash = (53 * hash) + getAdiu().hashCode();
      hash = (37 * hash) + CIFA_FIELD_NUMBER;
      hash = (53 * hash) + getCifa().hashCode();
      hash = (37 * hash) + DIU2_FIELD_NUMBER;
      hash = (53 * hash) + getDiu2().hashCode();
      hash = (37 * hash) + DIV_FIELD_NUMBER;
      hash = (53 * hash) + getDiv().hashCode();
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
      hash = (37 * hash) + SIV_FIELD_NUMBER;
      hash = (53 * hash) + getSiv().hashCode();
      hash = (37 * hash) + DIC_FIELD_NUMBER;
      hash = (53 * hash) + getDic().hashCode();
      hash = (37 * hash) + BID_F_FIELD_NUMBER;
      hash = (53 * hash) + getBIDF().hashCode();
      hash = (37 * hash) + STEPID_FIELD_NUMBER;
      hash = (53 * hash) + getStepid();
      hash = (37 * hash) + DIU3_FIELD_NUMBER;
      hash = (53 * hash) + getDiu3().hashCode();
      hash = (37 * hash) + SPM_FIELD_NUMBER;
      hash = (53 * hash) + getSpm().hashCode();
      hash = (37 * hash) + TID_FIELD_NUMBER;
      hash = (53 * hash) + getTid().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + DIBV_FIELD_NUMBER;
      hash = (53 * hash) + getDibv();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel().hashCode();
      hash = (37 * hash) + CLIENT_NETWORK_CLASS_FIELD_NUMBER;
      hash = (53 * hash) + getClientNetworkClass();
      hash = (37 * hash) + CSID_FIELD_NUMBER;
      hash = (53 * hash) + getCsid().hashCode();
      hash = (37 * hash) + ACCS_FIELD_NUMBER;
      hash = (53 * hash) + getAccs();
      hash = (37 * hash) + GSID_FIELD_NUMBER;
      hash = (53 * hash) + getGsid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Traffic parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Traffic parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Traffic parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Traffic parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Traffic parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Traffic parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Traffic parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Traffic parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Traffic parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Traffic parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Traffic prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Traffic}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Traffic)
        TrafficOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AmapEntity.internal_static_Traffic_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AmapEntity.internal_static_Traffic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Traffic.class, Builder.class);
      }

      // Construct using com.tazine.third.protobuf.compare.AmapEntity.Traffic.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ent_ = 0;

        dip_ = 0;

        diu_ = "";

        session_ = "";

        sign_ = "";

        aetraffic_ = 0;

        appstartid_ = "";

        adiu_ = "";

        cifa_ = "";

        diu2_ = "";

        div_ = "";

        output_ = "";

        siv_ = "";

        dic_ = "";

        bIDF_ = "";

        stepid_ = 0;

        diu3_ = "";

        spm_ = "";

        tid_ = "";

        uid_ = 0;

        dibv_ = 0;

        channel_ = "";

        clientNetworkClass_ = 0;

        csid_ = "";

        accs_ = 0;

        gsid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AmapEntity.internal_static_Traffic_descriptor;
      }

      public Traffic getDefaultInstanceForType() {
        return Traffic.getDefaultInstance();
      }

      public Traffic build() {
        Traffic result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Traffic buildPartial() {
        Traffic result = new Traffic(this);
        result.ent_ = ent_;
        result.dip_ = dip_;
        result.diu_ = diu_;
        result.session_ = session_;
        result.sign_ = sign_;
        result.aetraffic_ = aetraffic_;
        result.appstartid_ = appstartid_;
        result.adiu_ = adiu_;
        result.cifa_ = cifa_;
        result.diu2_ = diu2_;
        result.div_ = div_;
        result.output_ = output_;
        result.siv_ = siv_;
        result.dic_ = dic_;
        result.bIDF_ = bIDF_;
        result.stepid_ = stepid_;
        result.diu3_ = diu3_;
        result.spm_ = spm_;
        result.tid_ = tid_;
        result.uid_ = uid_;
        result.dibv_ = dibv_;
        result.channel_ = channel_;
        result.clientNetworkClass_ = clientNetworkClass_;
        result.csid_ = csid_;
        result.accs_ = accs_;
        result.gsid_ = gsid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Traffic) {
          return mergeFrom((Traffic)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Traffic other) {
        if (other == Traffic.getDefaultInstance()) return this;
        if (other.getEnt() != 0) {
          setEnt(other.getEnt());
        }
        if (other.getDip() != 0) {
          setDip(other.getDip());
        }
        if (!other.getDiu().isEmpty()) {
          diu_ = other.diu_;
          onChanged();
        }
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (!other.getSign().isEmpty()) {
          sign_ = other.sign_;
          onChanged();
        }
        if (other.getAetraffic() != 0) {
          setAetraffic(other.getAetraffic());
        }
        if (!other.getAppstartid().isEmpty()) {
          appstartid_ = other.appstartid_;
          onChanged();
        }
        if (!other.getAdiu().isEmpty()) {
          adiu_ = other.adiu_;
          onChanged();
        }
        if (!other.getCifa().isEmpty()) {
          cifa_ = other.cifa_;
          onChanged();
        }
        if (!other.getDiu2().isEmpty()) {
          diu2_ = other.diu2_;
          onChanged();
        }
        if (!other.getDiv().isEmpty()) {
          div_ = other.div_;
          onChanged();
        }
        if (!other.getOutput().isEmpty()) {
          output_ = other.output_;
          onChanged();
        }
        if (!other.getSiv().isEmpty()) {
          siv_ = other.siv_;
          onChanged();
        }
        if (!other.getDic().isEmpty()) {
          dic_ = other.dic_;
          onChanged();
        }
        if (!other.getBIDF().isEmpty()) {
          bIDF_ = other.bIDF_;
          onChanged();
        }
        if (other.getStepid() != 0) {
          setStepid(other.getStepid());
        }
        if (!other.getDiu3().isEmpty()) {
          diu3_ = other.diu3_;
          onChanged();
        }
        if (!other.getSpm().isEmpty()) {
          spm_ = other.spm_;
          onChanged();
        }
        if (!other.getTid().isEmpty()) {
          tid_ = other.tid_;
          onChanged();
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.getDibv() != 0) {
          setDibv(other.getDibv());
        }
        if (!other.getChannel().isEmpty()) {
          channel_ = other.channel_;
          onChanged();
        }
        if (other.getClientNetworkClass() != 0) {
          setClientNetworkClass(other.getClientNetworkClass());
        }
        if (!other.getCsid().isEmpty()) {
          csid_ = other.csid_;
          onChanged();
        }
        if (other.getAccs() != 0) {
          setAccs(other.getAccs());
        }
        if (!other.getGsid().isEmpty()) {
          gsid_ = other.gsid_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Traffic parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Traffic) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ent_ ;
      /**
       * <pre>
       * 同上
       * </pre>
       *
       * <code>optional int32 ent = 1;</code>
       */
      public int getEnt() {
        return ent_;
      }
      /**
       * <pre>
       * 同上
       * </pre>
       *
       * <code>optional int32 ent = 1;</code>
       */
      public Builder setEnt(int value) {
        
        ent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 同上
       * </pre>
       *
       * <code>optional int32 ent = 1;</code>
       */
      public Builder clearEnt() {
        
        ent_ = 0;
        onChanged();
        return this;
      }

      private int dip_ ;
      /**
       * <pre>
       * 同上
       * </pre>
       *
       * <code>optional int32 dip = 2;</code>
       */
      public int getDip() {
        return dip_;
      }
      /**
       * <pre>
       * 同上
       * </pre>
       *
       * <code>optional int32 dip = 2;</code>
       */
      public Builder setDip(int value) {
        
        dip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 同上
       * </pre>
       *
       * <code>optional int32 dip = 2;</code>
       */
      public Builder clearDip() {
        
        dip_ = 0;
        onChanged();
        return this;
      }

      private Object diu_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu = 3;</code>
       */
      public String getDiu() {
        Object ref = diu_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          diu_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDiuBytes() {
        Object ref = diu_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          diu_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu = 3;</code>
       */
      public Builder setDiu(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        diu_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu = 3;</code>
       */
      public Builder clearDiu() {
        
        diu_ = getDefaultInstance().getDiu();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu = 3;</code>
       */
      public Builder setDiuBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        diu_ = value;
        onChanged();
        return this;
      }

      private Object session_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public String getSession() {
        Object ref = session_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public Builder setSession(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string session = 4;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private Object sign_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string sign = 5;</code>
       */
      public String getSign() {
        Object ref = sign_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string sign = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string sign = 5;</code>
       */
      public Builder setSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string sign = 5;</code>
       */
      public Builder clearSign() {
        
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string sign = 5;</code>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sign_ = value;
        onChanged();
        return this;
      }

      private int aetraffic_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 aetraffic = 6;</code>
       */
      public int getAetraffic() {
        return aetraffic_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 aetraffic = 6;</code>
       */
      public Builder setAetraffic(int value) {
        
        aetraffic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 aetraffic = 6;</code>
       */
      public Builder clearAetraffic() {
        
        aetraffic_ = 0;
        onChanged();
        return this;
      }

      private Object appstartid_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string appstartid = 7;</code>
       */
      public String getAppstartid() {
        Object ref = appstartid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          appstartid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string appstartid = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAppstartidBytes() {
        Object ref = appstartid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appstartid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string appstartid = 7;</code>
       */
      public Builder setAppstartid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appstartid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string appstartid = 7;</code>
       */
      public Builder clearAppstartid() {
        
        appstartid_ = getDefaultInstance().getAppstartid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string appstartid = 7;</code>
       */
      public Builder setAppstartidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appstartid_ = value;
        onChanged();
        return this;
      }

      private Object adiu_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string adiu = 8;</code>
       */
      public String getAdiu() {
        Object ref = adiu_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          adiu_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string adiu = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAdiuBytes() {
        Object ref = adiu_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          adiu_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string adiu = 8;</code>
       */
      public Builder setAdiu(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        adiu_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string adiu = 8;</code>
       */
      public Builder clearAdiu() {
        
        adiu_ = getDefaultInstance().getAdiu();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string adiu = 8;</code>
       */
      public Builder setAdiuBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        adiu_ = value;
        onChanged();
        return this;
      }

      private Object cifa_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string cifa = 9;</code>
       */
      public String getCifa() {
        Object ref = cifa_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cifa_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string cifa = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCifaBytes() {
        Object ref = cifa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cifa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string cifa = 9;</code>
       */
      public Builder setCifa(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cifa_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string cifa = 9;</code>
       */
      public Builder clearCifa() {
        
        cifa_ = getDefaultInstance().getCifa();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string cifa = 9;</code>
       */
      public Builder setCifaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cifa_ = value;
        onChanged();
        return this;
      }

      private Object diu2_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu2 = 10;</code>
       */
      public String getDiu2() {
        Object ref = diu2_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          diu2_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu2 = 10;</code>
       */
      public com.google.protobuf.ByteString
          getDiu2Bytes() {
        Object ref = diu2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          diu2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu2 = 10;</code>
       */
      public Builder setDiu2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        diu2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu2 = 10;</code>
       */
      public Builder clearDiu2() {
        
        diu2_ = getDefaultInstance().getDiu2();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu2 = 10;</code>
       */
      public Builder setDiu2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        diu2_ = value;
        onChanged();
        return this;
      }

      private Object div_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string div = 11;</code>
       */
      public String getDiv() {
        Object ref = div_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          div_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string div = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDivBytes() {
        Object ref = div_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          div_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string div = 11;</code>
       */
      public Builder setDiv(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        div_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string div = 11;</code>
       */
      public Builder clearDiv() {
        
        div_ = getDefaultInstance().getDiv();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string div = 11;</code>
       */
      public Builder setDivBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        div_ = value;
        onChanged();
        return this;
      }

      private Object output_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string output = 12;</code>
       */
      public String getOutput() {
        Object ref = output_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          output_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string output = 12;</code>
       */
      public com.google.protobuf.ByteString
          getOutputBytes() {
        Object ref = output_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          output_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string output = 12;</code>
       */
      public Builder setOutput(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        output_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string output = 12;</code>
       */
      public Builder clearOutput() {
        
        output_ = getDefaultInstance().getOutput();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string output = 12;</code>
       */
      public Builder setOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        output_ = value;
        onChanged();
        return this;
      }

      private Object siv_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string siv = 13;</code>
       */
      public String getSiv() {
        Object ref = siv_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          siv_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string siv = 13;</code>
       */
      public com.google.protobuf.ByteString
          getSivBytes() {
        Object ref = siv_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          siv_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string siv = 13;</code>
       */
      public Builder setSiv(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siv_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string siv = 13;</code>
       */
      public Builder clearSiv() {
        
        siv_ = getDefaultInstance().getSiv();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string siv = 13;</code>
       */
      public Builder setSivBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siv_ = value;
        onChanged();
        return this;
      }

      private Object dic_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string dic = 14;</code>
       */
      public String getDic() {
        Object ref = dic_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dic_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string dic = 14;</code>
       */
      public com.google.protobuf.ByteString
          getDicBytes() {
        Object ref = dic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string dic = 14;</code>
       */
      public Builder setDic(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string dic = 14;</code>
       */
      public Builder clearDic() {
        
        dic_ = getDefaultInstance().getDic();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string dic = 14;</code>
       */
      public Builder setDicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dic_ = value;
        onChanged();
        return this;
      }

      private Object bIDF_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string BID_F = 15;</code>
       */
      public String getBIDF() {
        Object ref = bIDF_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bIDF_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string BID_F = 15;</code>
       */
      public com.google.protobuf.ByteString
          getBIDFBytes() {
        Object ref = bIDF_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bIDF_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string BID_F = 15;</code>
       */
      public Builder setBIDF(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bIDF_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string BID_F = 15;</code>
       */
      public Builder clearBIDF() {
        
        bIDF_ = getDefaultInstance().getBIDF();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string BID_F = 15;</code>
       */
      public Builder setBIDFBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bIDF_ = value;
        onChanged();
        return this;
      }

      private int stepid_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 stepid = 16;</code>
       */
      public int getStepid() {
        return stepid_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 stepid = 16;</code>
       */
      public Builder setStepid(int value) {
        
        stepid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 stepid = 16;</code>
       */
      public Builder clearStepid() {
        
        stepid_ = 0;
        onChanged();
        return this;
      }

      private Object diu3_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu3 = 17;</code>
       */
      public String getDiu3() {
        Object ref = diu3_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          diu3_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu3 = 17;</code>
       */
      public com.google.protobuf.ByteString
          getDiu3Bytes() {
        Object ref = diu3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          diu3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu3 = 17;</code>
       */
      public Builder setDiu3(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        diu3_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu3 = 17;</code>
       */
      public Builder clearDiu3() {
        
        diu3_ = getDefaultInstance().getDiu3();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string diu3 = 17;</code>
       */
      public Builder setDiu3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        diu3_ = value;
        onChanged();
        return this;
      }

      private Object spm_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string spm = 18;</code>
       */
      public String getSpm() {
        Object ref = spm_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          spm_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string spm = 18;</code>
       */
      public com.google.protobuf.ByteString
          getSpmBytes() {
        Object ref = spm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          spm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string spm = 18;</code>
       */
      public Builder setSpm(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        spm_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string spm = 18;</code>
       */
      public Builder clearSpm() {
        
        spm_ = getDefaultInstance().getSpm();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string spm = 18;</code>
       */
      public Builder setSpmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        spm_ = value;
        onChanged();
        return this;
      }

      private Object tid_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string tid = 19;</code>
       */
      public String getTid() {
        Object ref = tid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string tid = 19;</code>
       */
      public com.google.protobuf.ByteString
          getTidBytes() {
        Object ref = tid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string tid = 19;</code>
       */
      public Builder setTid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string tid = 19;</code>
       */
      public Builder clearTid() {
        
        tid_ = getDefaultInstance().getTid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string tid = 19;</code>
       */
      public Builder setTidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tid_ = value;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 uid = 20;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 uid = 20;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 uid = 20;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private int dibv_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 dibv = 21;</code>
       */
      public int getDibv() {
        return dibv_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 dibv = 21;</code>
       */
      public Builder setDibv(int value) {
        
        dibv_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 dibv = 21;</code>
       */
      public Builder clearDibv() {
        
        dibv_ = 0;
        onChanged();
        return this;
      }

      private Object channel_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string channel = 22;</code>
       */
      public String getChannel() {
        Object ref = channel_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string channel = 22;</code>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string channel = 22;</code>
       */
      public Builder setChannel(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string channel = 22;</code>
       */
      public Builder clearChannel() {
        
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string channel = 22;</code>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channel_ = value;
        onChanged();
        return this;
      }

      private int clientNetworkClass_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 client_network_class = 23;</code>
       */
      public int getClientNetworkClass() {
        return clientNetworkClass_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 client_network_class = 23;</code>
       */
      public Builder setClientNetworkClass(int value) {
        
        clientNetworkClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 client_network_class = 23;</code>
       */
      public Builder clearClientNetworkClass() {
        
        clientNetworkClass_ = 0;
        onChanged();
        return this;
      }

      private Object csid_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string csid = 24;</code>
       */
      public String getCsid() {
        Object ref = csid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          csid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string csid = 24;</code>
       */
      public com.google.protobuf.ByteString
          getCsidBytes() {
        Object ref = csid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          csid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string csid = 24;</code>
       */
      public Builder setCsid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        csid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string csid = 24;</code>
       */
      public Builder clearCsid() {
        
        csid_ = getDefaultInstance().getCsid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string csid = 24;</code>
       */
      public Builder setCsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        csid_ = value;
        onChanged();
        return this;
      }

      private int accs_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 accs = 25;</code>
       */
      public int getAccs() {
        return accs_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 accs = 25;</code>
       */
      public Builder setAccs(int value) {
        
        accs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 accs = 25;</code>
       */
      public Builder clearAccs() {
        
        accs_ = 0;
        onChanged();
        return this;
      }

      private Object gsid_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string gsid = 26;</code>
       */
      public String getGsid() {
        Object ref = gsid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gsid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string gsid = 26;</code>
       */
      public com.google.protobuf.ByteString
          getGsidBytes() {
        Object ref = gsid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gsid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string gsid = 26;</code>
       */
      public Builder setGsid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gsid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string gsid = 26;</code>
       */
      public Builder clearGsid() {
        
        gsid_ = getDefaultInstance().getGsid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional string gsid = 26;</code>
       */
      public Builder setGsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gsid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Traffic)
    }

    // @@protoc_insertion_point(class_scope:Traffic)
    private static final Traffic DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Traffic();
    }

    public static Traffic getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Traffic>
        PARSER = new com.google.protobuf.AbstractParser<Traffic>() {
      public Traffic parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Traffic(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Traffic> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Traffic> getParserForType() {
      return PARSER;
    }

    public Traffic getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Traffic_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Traffic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\namap.proto\"\222\003\n\007Traffic\022\013\n\003ent\030\001 \001(\005\022\013\n" +
      "\003dip\030\002 \001(\005\022\013\n\003diu\030\003 \001(\t\022\017\n\007session\030\004 \001(\t" +
      "\022\014\n\004sign\030\005 \001(\t\022\021\n\taetraffic\030\006 \001(\005\022\022\n\napp" +
      "startid\030\007 \001(\t\022\014\n\004adiu\030\010 \001(\t\022\014\n\004cifa\030\t \001(" +
      "\t\022\014\n\004diu2\030\n \001(\t\022\013\n\003div\030\013 \001(\t\022\016\n\006output\030\014" +
      " \001(\t\022\013\n\003siv\030\r \001(\t\022\013\n\003dic\030\016 \001(\t\022\r\n\005BID_F\030" +
      "\017 \001(\t\022\016\n\006stepid\030\020 \001(\005\022\014\n\004diu3\030\021 \001(\t\022\013\n\003s" +
      "pm\030\022 \001(\t\022\013\n\003tid\030\023 \001(\t\022\013\n\003uid\030\024 \001(\005\022\014\n\004di" +
      "bv\030\025 \001(\005\022\017\n\007channel\030\026 \001(\t\022\034\n\024client_netw" +
      "ork_class\030\027 \001(\005\022\014\n\004csid\030\030 \001(\t\022\014\n\004accs\030\031 ",
      "\001(\005\022\014\n\004gsid\030\032 \001(\tB/\n!com.tazine.third.pr" +
      "otobuf.compareB\nAmapEntityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Traffic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Traffic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Traffic_descriptor,
        new String[] { "Ent", "Dip", "Diu", "Session", "Sign", "Aetraffic", "Appstartid", "Adiu", "Cifa", "Diu2", "Div", "Output", "Siv", "Dic", "BIDF", "Stepid", "Diu3", "Spm", "Tid", "Uid", "Dibv", "Channel", "ClientNetworkClass", "Csid", "Accs", "Gsid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
